### ISSUE TITLE
One release triggered 3 action runnings?

### ISSUE THREAD

**Issue by Jeff-Tian** [skx/github-action-publish-binaries#10]
I created a release but 3 actions were running, is it normal?

![image](https://user-images.githubusercontent.com/3367820/67155468-c4ffcb80-f342-11e9-829d-05610fefd501.png)

**Comment by skx** [comment]
Not unexpected - you'll probably see that they all point to the same destination (at least they reference the same commit ID).

**Comment by Puyodead1** [comment]
Couln't you use:
```
on:
  release:
    types: [created]
```

to only run on one release event?

**Comment by skx** [comment]
Yes, that could be done.  I admit I didn't look into this in any detail just yet.

**Comment by skx** [comment]
Tested, and confirmed this works.  Updated README.

**Comment by Jeff-Tian** [comment]
> Couln't you use:
> 
> ```
> on:
>   release:
>     types: [created]
> ```
> 
> to only run on one release event?

Thank you.
