### ISSUE TITLE
Need Help Again: Action Not Successfully

### ISSUE THREAD

**Issue by Jeff-Tian** [skx/github-action-publish-binaries#12]
1. Use the latest version, it claims
```
##[error]Top level 'run:' section is required for /home/runner/work/_actions/skx/github-action-publish-binaries/master/action.yml
```

See: https://github.com/Jeff-Tian/me/commit/d7a22053b0055d31a54aace003d099ca5319544f/checks?check_suite_id=282525143

2. Use the 0.9, it claims aborting:
```
Processing file test/screenshot.gif
Upload URL is https://uploads.github.com/repos/Jeff-Tian/me/releases/20997129/assets?name=screenshot.gif
***************************
 upload was not successful.
 Aborting
***************************
{"url":"https://api.github.com/repos/Jeff-Tian/me/releases/assets/15746773","id":15746773,"node_id":"MDEyOlJlbGVhc2VBc3NldDE1NzQ2Nzcz","name":"screenshot.gif","label":"","uploader":{"login":"github-actions[bot]","id":41898282,"node_id":"MDM6Qm90NDE4OTgyODI=","avatar_url":"https://avatars2.githubusercontent.com/in/15368?v=4","gravatar_id":"","url":"https://api.github.com/users/github-actions%5Bbot%5D","html_url":"https://github.com/apps/github-actions","followers_url":"https://api.github.com/users/github-actions%5Bbot%5D/followers","following_url":"https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}","gists_url":"https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}","starred_url":"https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/github-actions%5Bbot%5D/subscriptions","organizations_url":"https://api.github.com/users/github-actions%5Bbot%5D/orgs","repos_url":"https://api.github.com/users/github-actions%5Bbot%5D/repos","events_url":"https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}","received_events_url":"https://api.github.com/users/github-actions%5Bbot%5D/received_events","type":"Bot","site_admin":false},"content_type":"application/octet-stream","state":"uploaded","size":97599,"download_count":0,"created_at":"2019-10-26T11:05:57Z","updated_at":"2019-10-26T11:05:57Z","browser_download_url":"https://github.com/Jeff-Tian/me/releases/download/v0.0.2/screenshot.gif"}
##[error]Docker run failed with exit code 1
```

See: https://github.com/Jeff-Tian/me/commit/ce6711775f945697c262d3c2fc2e8b0558e62b35/checks?check_suite_id=282527805

Thanks in advance!

**Comment by skx** [comment]
OK it looks like you have two issues:

* `Top level 'run:' section is required for.. github-action-publish-binaries/master/action.yml`
  * Which is a bug in my action-file.
* Upload failed, which is non-obvious.

Lemme attack the first one , and confirm.

**Comment by skx** [comment]
It looks like I was hasty in reading the documentation when I made the last release; I've now published a new action:

* https://github.com/skx/github-action-publish-binaries/releases/tag/release-0.13

That runs successfully on my test-project, generating:

* https://github.com/skx/upload-test/releases/tag/v0.0.6
  * Via the run https://github.com/skx/upload-test/commit/d52241717200888e3437a9e45fb20ac2fbce0fc4/checks?check_suite_id=282787999

I hope that means you can go back to using `master` and everything will just work.

Starting to feel a little sour on the whole actions setup at the moment, so fingers crossed :)

**Comment by Jeff-Tian** [comment]
Thanks!
