### ISSUE TITLE
##[error]Container action is only supported on Linux

### ISSUE THREAD

**Issue by CaiJingLong** [skx/github-action-publish-binaries#17]
I want to build a mac application and publish to release.

But I get the error log.

Have a plan to support non-linux platforms?

**Comment by skx** [comment]
I only use Linux myself, so I had no plans to change for this.

You might try something else.  e.g. https://github.com/actions/upload-artifact  But I don't know if that will be any better/different.

**Comment by CaiJingLong** [comment]
thx for reply. 
Use multi jobs can do it.
First job build and upload in macos.
Second job download and use the action.
