### ISSUE TITLE
400 - Bad Content-Length

### ISSUE THREAD

**Issue by passy** [skx/github-action-publish-binaries#19]
Hey, sorry for creating this as this has likely nothing to do with your action. I'm just curious if you or someone else has seen this, too.

https://github.com/facebook/flipper/runs/639683441?check_suite_focus=true

On our runs, the uploads keep failing because of `{"message":"Bad Content-Length: ","request_id":"0400:5CD8:10BA18:146B35:5EAE1646"}`. When trying to replicate the scenario by running effectively the same `curl` command locally, it works just fine. Any idea why these things might act up when run in the Github Action environment?

Please feel free to close this if this is out of scope for the action here!

**Comment by skx** [comment]
It looks a little bit like the report I saw previously in #5.

I don't see anything obviously wrong in [your  workflow](https://github.com/facebook/flipper/blob/master/.github/workflows/dmg-release.yml).

I did think there was an issue with a zero-sized file, due to confusion between:

* `dist/Flipper-mac.dmg`
* `Flipper-mac.dmg`

But now I see you've added the `ls -l` step, and the file does exist.

I suspect my action _is_ to blame, but it's a bit hard to know what is wrong :/

**Comment by passy** [comment]
Thanks so much for your reply, @skx! I had seen #5, too, but it seemed like a separate issue. We don't have a GitHub secret in our settings, and other workflows using it seem to be working fine.

The filename confusion was exactly the suspicion I had, as well, which is why I added the `ls -l` step right before. The weirdest part about all this to me is the exact error message: `Bad Content-Length: ` which looks to me like it concatenates the received content length - an empty string?

The only thing I could think of is that the file is relatively large (>90MB). Are you aware of any other uses of your action where rather chunky files are used?

**Comment by skx** [comment]
I have to say I've not seen examples of large files being used.  But now you mention it that _could_  be the reason for the failure.   Since you're already adding debugging-commands perhaps you could try this quick test:

```
..
..

- run: dd if=/dev/zero bs=1024k count=1024 of=1g.dmg
- run: dd if=/dev/zero bs=1024k count=10240 of=10g.dmg
..
..

    - name: Publish
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: *.dmg
```

**Comment by skx** [comment]
I guess without more information I'm gonna have to leave this hanging.

**Comment by passy** [comment]
Sorry for the delay. I'll give that a try!
