### ISSUE TITLE
More minimal docker base image

### ISSUE THREAD

**Issue by gjasny** [skx/github-action-publish-binaries#27]
Hi Steve,

I noticed that this action uses `golang` as the base image but could not spot any golang files. Maybe you could use a smaller image instead.

Thank you for the useful action.
-Gregor

**Comment by skx** [comment]
That's a fair point, thanks for the report!

At the time I created the action I was building and publishing golang applications, so it made sense as a quick hack to do it in one image - but of course it would make more sense to build and publish as two distinct actions, and that would allow shrinking this.

I'll make an update in the next couple of days to base this on something smaller.
