### ISSUE TITLE
Dependabot is confused about past releases

### ISSUE THREAD

**Issue by waja** [skx/github-action-publish-binaries#30]
[Dependabot can update](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) your github actions. While this is working nicely, it struggles with your action.
The cause are [releases](https://github.com/skx/github-action-publish-binaries/releases) like `release-1.3` and `release-1.2`, which are older then the actual `release-0.15` release. For example, see https://github.com/waja/monitoring-plugins-cyconet/pull/10.

Is there away to get this cleared up?

Many thanks, Jan.

**Comment by skx** [comment]
I'm open to suggestions, but off-hand I don't know what I should change here?

**Comment by waja** [comment]
On the first hand I see two options:
* stick with `release-0.xy` version scheme, then the higher versioned releases needs to be removed (or renamed)
* change versioning scheme and (re)start with something > `release-1.3`

**Comment by waja** [comment]
Seems to be fixed since the release-2.0.
