### ISSUE TITLE
Handle upload failure

### ISSUE THREAD

**Issue by varshavaradarajan** [skx/github-action-publish-binaries#6]
Upload artifacts failed with 

```
/usr/bin/docker run ...
Artifacts are already present, so not running the build-step
Processing file clusterlint-0.1.1-checksums.sha256
https://uploads.github.com/repos/digitalocean/clusterlint/releases/20593321/assets?name=clusterlint-0.1.1-checksums.sha256
{"message":"Not Found","request_id":"xyz,"documentation_url":"https://developer.github.com/v3"}
```
There could be many reasons why the upload fails: network issues, rate limits etc. 

Expected Results:
Script exits with 1 and the GH action step fails.

Actual Results:
The script exits with 0 which is misleading because the step passes and one assumes that artifacts are uploaded.

**Comment by skx** [comment]
OK to try to debug this I've [created a repository](https://github.com/skx/upload-test).  The repository has two artifacts in the top-level, `artifact-one` and `artifact-two`, and the included [workflow action](https://github.com/skx/upload-test/blob/master/.github/workflows/release.yml) tries to upload them both.

To make a release I added a tag, and pushed it:

```
frodo ~/upload-test $ git tag v0.0.1
frodo ~/upload-test $ git push --tags
```

Then I clicked on [the release-tab of the repository](https://github.com/skx/upload-test/releases/tag/v0.0.1) and edited/published it.

The end result was that the workflow ran - not sure if this is visble to other users :

* https://github.com/skx/upload-test/commit/0e7b6ba535d1e29838644248f363598cebc3fa38/checks?check_suite_id=262539562

And now the release contains those files:

* https://github.com/skx/upload-test/releases

I don't see a huge difference between or two upload-urls:

*  https://uploads.github.com/repos/digitalocean/clusterlint/releases/20593321/assets?name=clusterlint-0.1.1-checksums.sha256
* https://uploads.github.com/repos/skx/upload-test/releases/20660311/assets?name=artifact-two

And I see your most recent release does seem to have the right files:

* https://github.com/digitalocean/clusterlint/releases/tag/v0.1.1

So I'm a bit hazy on what is wrong:

* It looks like you have a v0.1.1 release.
  * This has the files.
* But you show an error.
  * So did it fail?

**Comment by skx** [comment]
Actually yes - your release artifacts __were__ uploaded, 3 days ago, in the link I gave above.

Here's the run-log:

* https://github.com/digitalocean/clusterlint/commit/56e3306cf7dee1dcd6955519936a93d70182b71d/checks?check_suite_id=258677626

To recap:

* You used my action.
* You configured it to upload `clusterlint-*`
* Those files __were__ uploaded.
* But you're seeing an error message logged.

I'm not sure if this is my fault, or githubs.  I suspect the latter ..

**Comment by varshavaradarajan** [comment]
@skx - I had to upload the files manually there. The upload failed with not found because of the token, but the step passed. I think that the upload script should be modified to fail the step if the curl to upload doesn't result in 200. WDYT?

**Comment by varshavaradarajan** [comment]
Thanks @skx!

**Comment by skx** [comment]
No problem, thanks for the report :)
